version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-net

  app:
    build: .
    container_name: todo-app
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      DB_HOST: todo-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo
    networks:
      - todo-net

volumes:
  postgres_data:

networks:
  todo-net:
    driver: bridge
